### ISSUE TITLE
Раздел про Аутентификацию на сайте backendinterview.ru не работает

### ISSUE THREAD

**Issue by Jumas-Cola** [arturpanteleev/phpInterview#26]
Странцы не открываются:

![image](https://github.com/user-attachments/assets/84801f5f-79d4-439e-85da-39406232db02)

Ссылки из оглавления ведут на неверные адреса:

![image](https://github.com/user-attachments/assets/8473badc-dc31-46db-be09-791a62acd23a)

**Comment by arturpanteleev** [comment]
мда) префикс проёбан
