### ISSUE TITLE
OS/Highload

### ISSUE THREAD

**Issue by arturpanteleev** [arturpanteleev/phpInterview#4]
Подумать над структурой и описать такие темы как:
- Асинхрноосить
- Блокирующий/неблокирущий вывод
- Конкурентность
- Балансировка

**Comment by yoshkin** [comment]
Когда ждать кэп?

**Comment by arturpanteleev** [comment]
Часть уже в os.md, про хайлод отдельно решил не делать.
Ни всегда можно пулл реквест сделать)

**Comment by yoshkin** [comment]
надо надо, народ требует)

**Comment by arturpanteleev** [comment]
Добавил инфу, нужно будет переорганизовать
